### ISSUE TITLE
The application needs a simple and user-firendly ui. Some elements in pages needs better adjustment and some color palettes should be set for certain parts of the application.

### ISSUE THREAD

**Issue by omertarakci** [SU-CS308-22FA/Group-13-FeedBall#7]

**Comment by bilgesucakir** [comment]
This issue is closed with the following commits:
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/54c626e4d045735d71af53df93e39d1e43383e6c">54c626e</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/e9a9e46be5259392f241e713474ce3c2e199712b">e9a9e46</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/71acc5a024fe67740dedf6eb7a2c5b0a03018350">71acc5a</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/1485c7b05fbcb562e210f3699f74df99c25ccf2f">1485c7b</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/2f6bd97a6e6312f07a2ff649e406f471f4893801">2f6bd97</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/c9e5d2f3d382b5cacd8d8788685a2fba03e326cc">c9e5d2f</a>
<a href="https://github.com/SU-CS308-22FA/Group-13-FeedBall/commit/6e950c1abbf2c6316cd2a696be4b0f954632cb10">6e950c1</a>
But some small adjustments may be done later on.
